/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Datasets
         * @description List all available datasets, optionally filtered by domain or environment.
         */
        get: operations["list_datasets_datasets__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset
         * @description Get details for a specific dataset.
         */
        get: operations["get_dataset_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Requests
         * @description List all requests, optionally filtered by status.
         */
        get: operations["list_requests_requests__get"];
        put?: never;
        /**
         * Create Request
         * @description Submit a new test data request.
         */
        post: operations["create_request_requests__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Request */
        get: operations["get_request_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Approve Request
         * @description Approve a pending request.
         */
        patch: operations["approve_request_requests__request_id__approve_patch"];
        trace?: never;
    };
    "/domains/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Domains
         * @description List all supported data domains. Filter by has_pii=true|false.
         */
        get: operations["list_domains_domains__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/domains/{domain_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Domain
         * @description Get full metadata for a specific domain including all fields and PII tags.
         */
        get: operations["get_domain_domains__domain_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/masking/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Masking Policies
         * @description List all active masking policies (one per domain).
         */
        get: operations["list_masking_policies_masking_policies_get"];
        put?: never;
        /**
         * Submit Masking Policy
         * @description Submit or replace a masking policy for a domain.
         *     If a policy already exists for the domain, its version is incremented.
         */
        post: operations["submit_masking_policy_masking_policies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/masking/policies/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Masking Policy
         * @description Get the active masking policy for a domain.
         */
        get: operations["get_masking_policy_masking_policies__domain__get"];
        /**
         * Update Masking Policy
         * @description Update an existing masking policy. Increments version.
         */
        put: operations["update_masking_policy_masking_policies__domain__put"];
        post?: never;
        /**
         * Delete Masking Policy
         * @description Remove the masking policy for a domain.
         */
        delete: operations["delete_masking_policy_masking_policies__domain__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/synthetic/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Synthetic Requests
         * @description List all synthetic data requests, optionally filtered by domain or status.
         */
        get: operations["list_synthetic_requests_synthetic_requests_get"];
        put?: never;
        /**
         * Create Synthetic Request
         * @description Submit a synthetic data generation request.
         *     If a Databricks pipeline job is configured, triggers a job run automatically.
         */
        post: operations["create_synthetic_request_synthetic_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/synthetic/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Synthetic Request
         * @description Get a synthetic request and refresh its status from Databricks if a run ID is set.
         */
        get: operations["get_synthetic_request_synthetic_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/synthetic/requests/{request_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cancel Synthetic Request
         * @description Cancel a queued synthetic request.
         */
        patch: operations["cancel_synthetic_request_synthetic_requests__request_id__cancel_patch"];
        trace?: never;
    };
    "/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description List recent TDM provisioning job runs.
         *     Returns live data from Databricks when configured, stub data otherwise.
         */
        get: operations["list_jobs_jobs__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Run
         * @description Get status of a specific job run.
         */
        get: operations["get_job_run_jobs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Job
         * @description Trigger a Databricks job run. Requires Databricks credentials.
         */
        post: operations["trigger_job_jobs_trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job Run
         * @description Cancel a running Databricks job run.
         */
        post: operations["cancel_job_run_jobs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineage/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Domain Lineage
         * @description Get pipeline lineage graph for a domain (S3 → Bronze → Silver).
         *     Column-level PII provenance is always returned.
         *     Enriched with live Unity Catalog metadata when Databricks is configured.
         */
        get: operations["get_domain_lineage_lineage__domain__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineage/{domain}/{table}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Table Lineage
         * @description Get lineage for a specific table within a domain (e.g. bronze_customer, silver_order).
         */
        get: operations["get_table_lineage_lineage__domain___table__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ColumnLineage */
        ColumnLineage: {
            /** Column */
            column: string;
            /** Pii */
            pii: boolean;
            /** Masked */
            masked: boolean;
            /** Masking Strategy */
            masking_strategy?: string | null;
            /** Source Column */
            source_column: string;
        };
        /** DataRequest */
        DataRequest: {
            /** Requester */
            requester: string;
            /** Domain */
            domain: string;
            /** Environment */
            environment: string;
            /** Row Count */
            row_count: number;
            /** Purpose */
            purpose?: string | null;
            /** Id */
            id: string;
            status: components["schemas"]["DataRequestStatus"];
            /**
             * Created At
             * @default
             */
            created_at: string;
        };
        /** DataRequestCreate */
        DataRequestCreate: {
            /** Requester */
            requester: string;
            /** Domain */
            domain: string;
            /** Environment */
            environment: string;
            /** Row Count */
            row_count: number;
            /** Purpose */
            purpose?: string | null;
        };
        /**
         * DataRequestStatus
         * @enum {string}
         */
        DataRequestStatus: "PENDING" | "APPROVED" | "REJECTED" | "FULFILLED";
        /** Dataset */
        Dataset: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Domain */
            domain: string;
            /** Environment */
            environment: string;
            /** Row Count */
            row_count: number;
            /** Masking Applied */
            masking_applied: boolean;
        };
        /** DatasetList */
        DatasetList: {
            /** Datasets */
            datasets: components["schemas"]["Dataset"][];
            /** Total */
            total: number;
        };
        /** Domain */
        Domain: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Fields */
            fields: components["schemas"]["DomainField"][];
            /** Pii Fields */
            pii_fields: string[];
            /** Supported Environments */
            supported_environments: string[];
            /** Estimated Row Count */
            estimated_row_count: number;
        };
        /** DomainField */
        DomainField: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Pii
             * @default false
             */
            pii: boolean;
            /**
             * Nullable
             * @default true
             */
            nullable: boolean;
        };
        /** DomainList */
        DomainList: {
            /** Domains */
            domains: components["schemas"]["Domain"][];
            /** Total */
            total: number;
        };
        /** FieldMaskingRule */
        FieldMaskingRule: {
            /** Field */
            field: string;
            strategy: components["schemas"]["MaskingStrategy"];
            /**
             * Preserve Format
             * @default false
             */
            preserve_format: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobRun */
        JobRun: {
            /** Run Id */
            run_id: string;
            /** Job Id */
            job_id: string;
            /** Job Name */
            job_name: string;
            status: components["schemas"]["JobRunStatus"];
            trigger: components["schemas"]["JobRunTrigger"];
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Pipeline Run Id */
            pipeline_run_id?: string | null;
            /** Error Message */
            error_message?: string | null;
        };
        /** JobRunList */
        JobRunList: {
            /** Runs */
            runs: components["schemas"]["JobRun"][];
            /** Total */
            total: number;
        };
        /**
         * JobRunStatus
         * @enum {string}
         */
        JobRunStatus: "PENDING" | "RUNNING" | "SUCCESS" | "FAILED" | "SKIPPED";
        /**
         * JobRunTrigger
         * @enum {string}
         */
        JobRunTrigger: "manual" | "schedule" | "api";
        /** JobTriggerRequest */
        JobTriggerRequest: {
            /** Job Id */
            job_id: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
        };
        /** LineageEdge */
        LineageEdge: {
            /** From Node */
            from_node: string;
            /** To Node */
            to_node: string;
            /** Transform */
            transform: string;
        };
        /** LineageNode */
        LineageNode: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            type: components["schemas"]["LineageNodeType"];
            /** Catalog */
            catalog?: string | null;
            /** Schema Name */
            schema_name?: string | null;
            /** Location */
            location?: string | null;
        };
        /**
         * LineageNodeType
         * @enum {string}
         */
        LineageNodeType: "source" | "bronze" | "silver" | "gold" | "s3";
        /** MaskingPolicy */
        MaskingPolicy: {
            /** Domain */
            domain: string;
            /** Rules */
            rules: components["schemas"]["FieldMaskingRule"][];
            /** Created By */
            created_by: string;
            /** Id */
            id: string;
            /** Version */
            version: number;
            /** Created At */
            created_at: string;
        };
        /** MaskingPolicyCreate */
        MaskingPolicyCreate: {
            /** Domain */
            domain: string;
            /** Rules */
            rules: components["schemas"]["FieldMaskingRule"][];
            /** Created By */
            created_by: string;
        };
        /**
         * MaskingStrategy
         * @enum {string}
         */
        MaskingStrategy: "hash" | "redact" | "nullify" | "partial";
        /** SyntheticRequest */
        SyntheticRequest: {
            /** Domain */
            domain: string;
            /** Row Count */
            row_count: number;
            /** Environment */
            environment: string;
            /**
             * Locale
             * @default en_US
             */
            locale: string;
            /** Seed */
            seed?: number | null;
            /** Requester */
            requester: string;
            /** Id */
            id: string;
            status: components["schemas"]["SyntheticStatus"];
            /** Output Path */
            output_path?: string | null;
            /** Job Run Id */
            job_run_id?: string | null;
            /** Created At */
            created_at: string;
        };
        /** SyntheticRequestCreate */
        SyntheticRequestCreate: {
            /** Domain */
            domain: string;
            /** Row Count */
            row_count: number;
            /** Environment */
            environment: string;
            /**
             * Locale
             * @default en_US
             */
            locale: string;
            /** Seed */
            seed?: number | null;
            /** Requester */
            requester: string;
        };
        /**
         * SyntheticStatus
         * @enum {string}
         */
        SyntheticStatus: "QUEUED" | "RUNNING" | "COMPLETE" | "FAILED";
        /** TableLineage */
        TableLineage: {
            /** Table */
            table: string;
            /** Domain */
            domain: string;
            /** Nodes */
            nodes: components["schemas"]["LineageNode"][];
            /** Edges */
            edges: components["schemas"]["LineageEdge"][];
            /** Columns */
            columns: components["schemas"]["ColumnLineage"][];
            /** Pipeline Run Id */
            pipeline_run_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_datasets_datasets__get: {
        parameters: {
            query?: {
                domain?: string;
                environment?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requests_requests__get: {
        parameters: {
            query?: {
                status?: components["schemas"]["DataRequestStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRequest"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_requests__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataRequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_request_requests__request_id__approve_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_domains_domains__get: {
        parameters: {
            query?: {
                has_pii?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_domain_domains__domain_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_masking_policies_masking_policies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaskingPolicy"][];
                };
            };
        };
    };
    submit_masking_policy_masking_policies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaskingPolicyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaskingPolicy"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_masking_policy_masking_policies__domain__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaskingPolicy"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_masking_policy_masking_policies__domain__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaskingPolicyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaskingPolicy"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_masking_policy_masking_policies__domain__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_synthetic_requests_synthetic_requests_get: {
        parameters: {
            query?: {
                domain?: string;
                status?: components["schemas"]["SyntheticStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyntheticRequest"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_synthetic_request_synthetic_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyntheticRequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyntheticRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_synthetic_request_synthetic_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyntheticRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_synthetic_request_synthetic_requests__request_id__cancel_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyntheticRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_jobs__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_run_jobs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_job_jobs_trigger_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobTriggerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_run_jobs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_domain_lineage_lineage__domain__get: {
        parameters: {
            query?: {
                catalog?: string;
                schema?: string;
                pipeline_run_id?: string;
            };
            header?: never;
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableLineage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_table_lineage_lineage__domain___table__get: {
        parameters: {
            query?: {
                catalog?: string;
                schema?: string;
            };
            header?: never;
            path: {
                domain: string;
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableLineage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
